name: flutterSky
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  google_maps_flutter: ^2.5.3
  provider: ^6.1.2
  flutter_spinkit: ^5.2.1
  flutter_animate: ^4.5.0
  confetti: ^0.7.0
  smooth_page_indicator: ^1.2.1
  google_fonts: ^6.1.0
  weather_icons: ^3.0.0
  fluttertoast: ^8.2.12
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  flutter_map_cancellable_tile_provider: ^3.0.2
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
#    - assets/images/
    - assets/images/logo_black.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#    - family: GreatVibes
#      fonts:
#        - asset: fonts/GreatVibes-Regular.ttf
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
